# PostWarps 主配置文件
# 作者: postyizhan

# 更新检查设置
update-checker:
  # 是否启用更新检查
  enabled: true
  # 检查频率（天）
  check-interval-days: 1

# 语言 支持的语言：https://github.com/postyizhan/PostWarps/tree/main/src/main/resources/lang
language: zh_CN

# 数据库设置
database:
  # 数据库类型: SQLite 或 MySQL
  type: "SQLite"
  
  # MySQL 设置 (如果使用MySQL)
  mysql:
    host: "localhost"
    port: 3306
    database: "postwarps"
    username: "root"
    password: "password"
    # 是否使用SSL连接
    use-ssl: false
    # 连接池大小
    pool-size: 10

# 调试模式
debug: false
